/**
 * The canned vibe-mode cluster workflow script, executed by the workflow
 * engine. The runtime provides `agent`, `parallel`, `pipeline`, `phase`,
 * `log`, and the `args` global (the tool call's `{ request, answers }`).
 *
 * The script text is a constant: the tool feeds it to the engine verbatim.
 * It deliberately uses string concatenation and double-quoted strings so the
 * constant never needs escape handling for template-literal syntax.
 */

export const VIBE_WORKFLOW_SCRIPT: string = [
  'const request = String(args.request ?? "")',
  'const answers = (args.answers ?? {})',
  'const prefillRequirements = (args.requirements ?? null)',
  'const prefillDesign = (args.design ?? null)',
  'const prefillStyleGuide = (args.styleGuide ?? null)',
  '',
  'phase("product")',
  'const pm = prefillRequirements !== null',
  '  ? prefillRequirements',
  '  : await agent(',
  '    "You are the PRODUCT MANAGER in a fixed agent cluster working on the user request below. Infer the latent requirements, ask the user about anything materially ambiguous, and produce the requirements archive.\\n"',
  '    + "USER REQUEST: " + request + "\\n"',
  '    + (Object.keys(answers).length > 0',
  '      ? "USER DECISIONS (already answered, do not re-ask): " + JSON.stringify(answers)',
  '      : "If anything material is ambiguous, ask the user directly with the ask_user tool. If the ask_user tool is unavailable, list the open questions instead of guessing.")',
  '    + "\\nReturn the requirements archive as JSON: { title, goal, requirements: [{ id, description, priority }], assumptions: [string], openQuestions: [{ id, question, options: [string] }] }. openQuestions is empty when everything is clear.",',
  '    { label: "product-manager", phase: "product", schema: { type: "object", properties: { title: { type: "string" }, goal: { type: "string" }, requirements: { type: "array", items: { type: "object", properties: { id: { type: "string" }, description: { type: "string" }, priority: { type: "string" } }, required: ["id", "description", "priority"] } }, assumptions: { type: "array", items: { type: "string" } }, openQuestions: { type: "array", items: { type: "object", properties: { id: { type: "string" }, question: { type: "string" }, options: { type: "array", items: { type: "string" } } }, required: ["id", "question"] } } }, required: ["title", "goal", "requirements", "assumptions", "openQuestions"] } },',
  '  )',
  'if (pm === null) return { stage: "failed", phase: "product", reason: "product manager agent failed" }',
  'if ((pm.openQuestions ?? []).length > 0 && Object.keys(answers).length === 0) {',
  '  return { stage: "needs-input", requirements: pm, openQuestions: pm.openQuestions }',
  '}',
  '',
  'phase("design")',
  'const designJobs = []',
  'let ui = prefillStyleGuide',
  'let arch = prefillDesign',
  'if (ui === null) designJobs.push(() => agent(',
  '  "You are the UI DESIGNER in a fixed agent cluster. Produce the style guide for the product below; frontend engineers follow it as their design contract.\\n"',
  '  + "REQUIREMENTS ARCHIVE: " + JSON.stringify(pm)',
  '  + "\\nIf the visual direction is ambiguous, ask the user with the ask_user tool; if unavailable, choose tasteful defaults and note them.\\nReturn the style guide as JSON: { stylePrinciples: [string], colors: { primary, secondary, accent, background, text }, typography: string, spacing: string, motion: string, animationStyle: string, components: [{ name, spec }] }.",',
  '  { label: "ui-designer", phase: "design", schema: { type: "object", properties: { stylePrinciples: { type: "array", items: { type: "string" } }, colors: { type: "object", properties: { primary: { type: "string" }, secondary: { type: "string" }, accent: { type: "string" }, background: { type: "string" }, text: { type: "string" } }, required: ["primary", "secondary", "accent", "background", "text"] }, typography: { type: "string" }, spacing: { type: "string" }, motion: { type: "string" }, animationStyle: { type: "string" }, components: { type: "array", items: { type: "object", properties: { name: { type: "string" }, spec: { type: "string" } }, required: ["name", "spec"] } } }, required: ["stylePrinciples", "colors", "typography", "spacing", "motion", "animationStyle", "components"] } },',
  '))',
  'if (arch === null) designJobs.push(() => agent(',
  '  "You are the ARCHITECT in a fixed agent cluster. Produce the technical design for the requirements archive below: choose the tech stack, sketch the architecture, decompose the work into small parallelizable modules, and define the process.\\n"',
  '  + "REQUIREMENTS ARCHIVE: " + JSON.stringify(pm)',
  '  + "\\nReturn the technical design as JSON: { techStack: [string], architecture: string, modules: [{ id, title, layer, tasks: [string], acceptance: string }], process: string, risks: [string] }. layer is frontend, backend, or both; split the work so multiple engineers can implement modules in parallel.",',
  '  { label: "architect", phase: "design", schema: { type: "object", properties: { techStack: { type: "array", items: { type: "string" } }, architecture: { type: "string" }, modules: { type: "array", items: { type: "object", properties: { id: { type: "string" }, title: { type: "string" }, layer: { type: "string" }, tasks: { type: "array", items: { type: "string" } }, acceptance: { type: "string" } }, required: ["id", "title", "layer", "tasks", "acceptance"] } }, process: { type: "string" }, risks: { type: "array", items: { type: "string" } } }, required: ["techStack", "architecture", "modules", "process", "risks"] } },',
  '))',
  'const designResults = designJobs.length > 0 ? await parallel(designJobs) : []',
  'if (ui === null) ui = designResults.shift() ?? null',
  'if (arch === null) arch = designResults.shift() ?? null',
  'if (ui === null || arch === null) return { stage: "failed", phase: "design", reason: "design phase agent failed" }',
  'if (!Array.isArray(arch.modules)) return { stage: "failed", phase: "design", reason: "prefilled design has no modules array" }',
  '',
  'phase("implement")',
  'const engineerJobs = []',
  'for (const module of arch.modules) {',
  '  const layers = module.layer === "both" ? ["frontend", "backend"] : [module.layer]',
  '  for (const layer of layers) {',
  '    engineerJobs.push(() => agent(',
  '      "You are the " + layer + " ENGINEER in a fixed agent cluster. Implement module " + module.id + " of the design below, in small parts with a per-part unit test for each part as you go. Use the filesystem and shell tools; if they are unavailable, deliver the code as text.\\n"',
  '      + "MODULE: " + JSON.stringify(module)',
  '      + "\\nARCHITECTURE: " + JSON.stringify(arch)',
  '      + (layer === "frontend" ? "\\nSTYLE GUIDE: " + JSON.stringify(ui) : ""),',
  '      { label: "engineer-" + module.id + "-" + layer, phase: "implement", schema: { type: "object", properties: { module: { type: "string" }, files: { type: "array", items: { type: "string" } }, tests: { type: "array", items: { type: "object", properties: { name: { type: "string" }, outcome: { type: "string" } }, required: ["name", "outcome"] } }, issues: { type: "array", items: { type: "string" } } }, required: ["module", "files", "tests", "issues"] } },',
  '    ))',
  '  }',
  '}',
  'const engineers = await parallel(engineerJobs)',
  'if (engineers.some(engineer => engineer === null)) return { stage: "failed", phase: "implement", reason: "an engineer agent failed" }',
  '',
  'phase("test")',
  'const qa = await agent(',
  '  "You are the TEST ENGINEER in a fixed agent cluster. Review the whole delivery below and run the project tests where possible; if the shell is unavailable, review statically and say so.\\n"',
  '  + "DELIVERY: " + JSON.stringify({ requirements: pm, ui: ui, architecture: arch, engineers: engineers })',
  '  + "\\nReturn the review as JSON: { passed: boolean, issues: [{ module, severity, description }], report: string }. severity is high, medium, or low.",',
  '  { label: "test-engineer", phase: "test", schema: { type: "object", properties: { passed: { type: "boolean" }, issues: { type: "array", items: { type: "object", properties: { module: { type: "string" }, severity: { type: "string" }, description: { type: "string" } }, required: ["module", "severity", "description"] } }, report: { type: "string" } }, required: ["passed", "issues", "report"] } },',
  ')',
  'if (qa === null) return { stage: "failed", phase: "test", reason: "test engineer agent failed" }',
  '',
  'let escalated = null',
  'if (!qa.passed && qa.issues.length > 0) {',
  '  phase("escalate")',
  '  const fixPlan = await agent(',
  '    "You are the ARCHITECT in the fixed agent cluster again. The test engineer found issues; assign fixes back to the responsible modules.\\n"',
  '    + "ISSUES: " + JSON.stringify(qa.issues)',
  '    + "\\nReturn the remediation plan as JSON: { modules: [{ id, fixes: [string] }] }.",',
  '    { label: "architect-remediation", phase: "escalate", schema: { type: "object", properties: { modules: { type: "array", items: { type: "object", properties: { id: { type: "string" }, fixes: { type: "array", items: { type: "string" } } }, required: ["id", "fixes"] } } }, required: ["modules"] } },',
  '  )',
  '  if (fixPlan === null) return { stage: "failed", phase: "escalate", reason: "architect remediation agent failed" }',
  '  phase("fix")',
  '  const fixJobs = []',
  '  for (const fix of fixPlan.modules) {',
  '    fixJobs.push(() => agent(',
  '      "You are the ENGINEER in the fixed agent cluster again. Apply the assigned fixes to module " + fix.id + ": " + JSON.stringify(fix.fixes) + ". Update the unit tests to match. Use the filesystem and shell tools; if unavailable, deliver the fixed code as text.\\nReturn the fix report as JSON: { module: string, applied: [string], tests: [{ name, outcome }], issues: [string] }.",',
  '      { label: "fix-" + fix.id, phase: "fix", schema: { type: "object", properties: { module: { type: "string" }, applied: { type: "array", items: { type: "string" } }, tests: { type: "array", items: { type: "object", properties: { name: { type: "string" }, outcome: { type: "string" } }, required: ["name", "outcome"] } }, issues: { type: "array", items: { type: "string" } } }, required: ["module", "applied", "tests", "issues"] } },',
  '    ))',
  '  }',
  '  const fixes = await parallel(fixJobs)',
  '  if (fixes.some(fix => fix === null)) return { stage: "failed", phase: "fix", reason: "a fix engineer agent failed" }',
  '  phase("verify")',
  '  const verification = await agent(',
  '    "You are the TEST ENGINEER in the fixed agent cluster again. Verify the applied fixes resolved the reported issues.\\n"',
  '    + "FIXES: " + JSON.stringify(fixes)',
  '    + "\\nReturn the verification as JSON: { passed: boolean, remainingIssues: [string], report: string }.",',
  '    { label: "test-engineer-verify", phase: "verify", schema: { type: "object", properties: { passed: { type: "boolean" }, remainingIssues: { type: "array", items: { type: "string" } }, report: { type: "string" } }, required: ["passed", "remainingIssues", "report"] } },',
  '  )',
  '  if (verification === null) return { stage: "failed", phase: "verify", reason: "verification agent failed" }',
  '  escalated = { fixPlan: fixPlan, fixes: fixes, verification: verification }',
  '}',
  '',
  'return {',
  '  stage: "done",',
  '  requirements: pm,',
  '  styleGuide: ui,',
  '  architecture: arch,',
  '  engineers: engineers,',
  '  testReport: qa,',
  '  escalated: escalated,',
  '}',
].join('\n')
